image: node:18

# Cache dependencies untuk mempercepat build
cache:
  paths:
    - node_modules/

pages:
  script:
    - npm ci
    - npm run build
    - mv dist public   # Vite build output ke dist, tapi GitLab Pages baca dari "public"
  artifacts:
    paths:
      - public
  only:
    - main   # Ganti jika default branch kamu bukan 'main'
