version: '3.8'

services:
  project-test-frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: project-test-frontend
    expose:
      - "3000"
    restart: unless-stopped

  certbot:
    image: certbot/certbot
    container_name: certbot
    volumes:
      - ./certbot/www:/var/www/certbot
      - ./certbot/conf:/etc/letsencrypt
    depends_on:
      - project-test-frontend
    command: >
      certbot certonly --webroot 
      --webroot-path=/var/www/certbot 
      --email damarmuhamad13@gmail.com 
      --agree-tos 
      --no-eff-email 
      -d project-test.damar-galih.tech